# Generated by Django 4.2 on 2024-04-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
